apiVersion: v1
data:
  access_key_id: .
  access_key_secret: .
  bucketnames: .
  endpoint: .
  forcepathstyle: dHJ1ZQ==
  region: dXMtd2VzdC0x # if not us-east-1
kind: Secret
metadata:
  name: s3-storage
  namespace: openshift-logging
type: Opaque
